[program:laravel-worker]
command=sh -c ". /etc/environment; php /var/www/html/base/artisan queue:work --sleep=3 --tries=3"
directory=/var/www/html/base

autostart=true
autorestart=true
user=root

stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
